# om namah shivaya

service: default
runtime: nodejs16
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.90
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
